ALTER TYPE "public"."genre" ADD VALUE 'HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TRANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DNB';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DUBSTEP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GARAGE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BREAKBEAT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'IDM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SYNTHWAVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DOWNTEMPO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARDSTYLE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOOMBAP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TRAP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DRILL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CLOUDRAP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PHONK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEOSOUL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOUL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ALTERNATIVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POSTPUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PSYCHEDELIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SHOEGAZE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GRUNGE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PROGROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HEAVYMETAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DEATHMETAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BLACKMETAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DOOM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'METALCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POSTMETAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'INDIEPOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SYNTHPOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HYPERPOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DREAMPOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BEBOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FUSION';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SWING';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ORCHESTRAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CINEMATIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEOCLASSICAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'OPERA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PIANO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ACOUSTIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SINGER_SONGWRITER';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'COUNTRY';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'WORLD';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NOISE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DRONE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'INDUSTRIAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'REGGAE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DUB';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOUNDTRACK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SPOKENWORD';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'DREAMY';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'AGGRESSIVE';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'UPLIFTING';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'SAD';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'GROOVY';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'MEDITATIVE';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'TENSE';--> statement-breakpoint
ALTER TYPE "public"."mood" ADD VALUE 'PLAYFUL';