ALTER TYPE "public"."genre" ADD VALUE 'ACID';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ACID_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BEATDOWN';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DEEP_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ELECTRO_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EURO_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GARAGE_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GHETTO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GHETTO_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARD_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HIP_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ITALO_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PROGRESSIVE_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TECH_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TRIBAL_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TROPICAL_HOUSE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BLEEP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DEEP_TECHNO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DUB_TECHNO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARD_TECHNO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MINIMAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MINIMAL_TECHNO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SCHRANZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GOA_TRANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARD_TRANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PROGRESSIVE_TRANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PSY_TRANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TECH_TRANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARDCORE_EDM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GABBER';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HAPPY_HARDCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SPEEDCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DONK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HANDS_UP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JUMPSTYLE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MAKINA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BASSLINE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SPEED_GARAGE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GRIME';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JUNGLE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HALFTIME';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BREAKCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BROKEN_BEAT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BIG_BEAT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PROGRESSIVE_BREAKS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JUKE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ELECTRO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DARK_AMBIENT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEW_AGE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BERLIN_SCHOOL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ILLBIENT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CHILLWAVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TRIP_HOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DUNGEON_SYNTH';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GLITCH';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LEFTFIELD';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FUTURE_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ACID_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JAZZDANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DISCO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EURO_DISCO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ITALO_DISCO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NU_DISCO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HI_NRG';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EUROBEAT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EURODANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ITALODANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DISCO_POLO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DANCE_POP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FREESTYLE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ELECTROCLASH';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DARKWAVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEW_WAVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEW_BEAT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EBM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'VAPORWAVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CHIPTUNE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MUSIQUE_CONCRETE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POWER_ELECTRONICS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RHYTHMIC_NOISE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOUND_COLLAGE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TRIBAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BASS_MUSIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOUNCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BRITCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CONSCIOUS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CRUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CUT_UP_DJ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'G_FUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GANGSTA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARDCORE_HIPHOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HORRORCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'INSTRUMENTAL_HIPHOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JAZZY_HIPHOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MIAMI_BASS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POP_RAP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RAGGA_HIPHOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SCREW';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TURNTABLISM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'AFROBEAT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOOGIE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FREE_FUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'P_FUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PSYCHEDELIC_SOUL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEW_JACK_SWING';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'UK_STREET_SOUL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GOSPEL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ACID_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'AOR';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ARENA_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ART_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BEAT';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BLUES_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BRITPOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CLASSIC_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'COLDWAVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'COUNTRY_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DEATHROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DOO_WOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EMO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ETHEREAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FOLK_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GARAGE_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GLAM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GOTH_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARD_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'KRAUTROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LOUNGE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MATH_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MOD';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NO_WAVE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POP_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POST_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POWER_POP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PSYCHOBILLY';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PUB_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ROCK_N_ROLL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ROCKABILLY';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOFT_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOUTHERN_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SPACE_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'STONER_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SURF';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SYMPHONIC_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TWIST';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'YEYE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARDCORE_PUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MELODIC_HARDCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POST_HARDCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POP_PUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'OI';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CRUST';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POWER_VIOLENCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NOISECORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ATMOSPHERIC_BLACK_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DEPRESSIVE_BLACK_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'VIKING_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MELODIC_DEATH_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TECHNICAL_DEATH_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DEATHCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GRINDCORE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FUNERAL_DOOM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SLUDGE_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NU_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FOLK_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FUNK_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GOTHIC_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POWER_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PROGRESSIVE_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SPEED_METAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'THRASH';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BALLAD';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BUBBLEGUM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CHANSON';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CITY_POP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EUROPOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'J_POP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'K_POP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'KAYOKYOKU';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SCHLAGER';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'VOCAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NOVELTY';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LIGHT_MUSIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MUSIC_HALL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOLLYWOOD';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'AFRO_CUBAN_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'AVANTGARDE_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BIG_BAND';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOSSA_NOVA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CONTEMPORARY_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'COOL_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DIXIELAND';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'EASY_LISTENING';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FREE_IMPROVISATION';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FREE_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GYPSY_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARD_BOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JAZZ_FUNK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JAZZ_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LATIN_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MODAL_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POST_BOP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RAGTIME';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SMOOTH_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOUL_JAZZ';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SPACE_AGE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOOGIE_WOOGIE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CHICAGO_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'COUNTRY_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DELTA_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ELECTRIC_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HARMONICA_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'JUMP_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LOUISIANA_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MODERN_ELECTRIC_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PIANO_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TEXAS_BLUES';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BAROQUE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CHORAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CONTEMPORARY_CLASSICAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'IMPRESSIONIST';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MEDIEVAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MODERN_CLASSICAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEO_ROMANTIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POST_MODERN_CLASSICAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RENAISSANCE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ROMANTICISM';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BLUEGRASS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CAJUN';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CELTIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HILLBILLY';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HONKY_TONK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'POLKA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'VOLKSMUSIK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NEOFOLK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'AFRICAN';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CANZONE_NAPOLETANA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CATALAN_MUSIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FADO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FLAMENCO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HIGHLIFE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'HINDUSTANI';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'INDIAN_CLASSICAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LAIKO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NORDIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PACIFIC';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RAI';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ROMANI';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOUKOUS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SEGA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ZOUK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ENTEKHNO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LATIN';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'AFRO_CUBAN';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BAIAO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BATUCADA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BEGUINE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOLERO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BOOGALOO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CHA_CHA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CHARANGA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'COMPAS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CUBANO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CUMBIA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DESCARGA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FORRO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GUAGUANCO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GUAJIRA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'GUARACHA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MPB';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MAMBO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MARIACHI';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MERENGUE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NORTENO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'NUEVA_CANCION';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PACHANGA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'PORRO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RANCHERA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'REGGAETON';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RUMBA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SALSA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SAMBA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SON';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SON_MONTUNO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TANGO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'TEJANO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'VALLENATO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'CALYPSO';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'DANCEHALL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'LOVERS_ROCK';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'RAGGA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'REGGAE_POP';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ROCKSTEADY';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'ROOTS_REGGAE';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SKA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'SOCA';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'MUSICAL';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'BRASS';--> statement-breakpoint
ALTER TYPE "public"."genre" ADD VALUE 'FIELD_RECORDING';