export { db, ping } from './client';
export type { DB } from './client';
export * from './schema';
export * from './repositories/artist';
export * from './repositories/release';
export * from './repositories/track';
export { getTrackAudio, trackExists } from './queries/track-audio';
export type { TrackAudioData } from './queries/track-audio';
export { listActiveArtists } from './queries/artists';
export type { ArtistListItem } from './queries/artists';
export { getLikeState, getLikeCount, likeTrack, unlikeTrack } from './queries/likes';
export { getFollowState, getFollowerCount, followArtist, unfollowArtist } from './queries/follows';
export { getFeed } from './queries/feed';
export type { FeedRelease } from './queries/feed';
export { insertPlayEvent } from './queries/play-events';
export type { InsertPlayEventData } from './queries/play-events';
export type { InferSelectModel, InferInsertModel } from 'drizzle-orm';
