// Клиентский модуль жанров. Тип — type-only импорт из @vire/core (стирается при
// компиляции, runtime-код core в клиентский бандл не попадает). Здесь — группировка
// и подписи для UI: список большой, пикеры показывают его по категориям + поиск.
// Полнота GENRE_LABELS гарантируется типом Record<Genre, string>; равенство состава
// групп зеркалам core/db — тестом lib/__tests__/genres.test.ts.

import type { Genre } from '@vire/core';

export type { Genre };

export interface GenreGroup {
  label: string;
  genres: Genre[];
}

// Общий лимит жанров на трек — используется пикером артиста и формой админки.
export const MAX_TRACK_GENRES = 3;

// Группировка для UI. Порядок здесь же определяет порядок в пикерах и <optgroup>.
// Каждый жанр ровно в одной группе (разбиение — проверяется тестом).
export const GENRE_GROUPS: GenreGroup[] = [
  {
    label: 'Хаус',
    genres: [
      'HOUSE', 'DEEP_HOUSE', 'TECH_HOUSE', 'PROGRESSIVE_HOUSE', 'ELECTRO_HOUSE',
      'ACID_HOUSE', 'ACID', 'GARAGE_HOUSE', 'EURO_HOUSE', 'ITALO_HOUSE', 'HARD_HOUSE',
      'HIP_HOUSE', 'GHETTO_HOUSE', 'GHETTO', 'TRIBAL_HOUSE', 'TROPICAL_HOUSE', 'BEATDOWN',
    ],
  },
  {
    label: 'Техно',
    genres: ['TECHNO', 'MINIMAL_TECHNO', 'MINIMAL', 'DEEP_TECHNO', 'DUB_TECHNO', 'HARD_TECHNO', 'SCHRANZ', 'BLEEP'],
  },
  {
    label: 'Транс',
    genres: ['TRANCE', 'PROGRESSIVE_TRANCE', 'PSY_TRANCE', 'GOA_TRANCE', 'HARD_TRANCE', 'TECH_TRANCE'],
  },
  {
    label: 'Бас, брейкбит и гараж',
    genres: [
      'DNB', 'JUNGLE', 'DUBSTEP', 'HALFTIME', 'GARAGE', 'SPEED_GARAGE', 'BASSLINE',
      'GRIME', 'BREAKBEAT', 'BIG_BEAT', 'BREAKCORE', 'BROKEN_BEAT', 'PROGRESSIVE_BREAKS',
      'JUKE', 'ELECTRO',
    ],
  },
  {
    label: 'Хардкор и хардстайл',
    genres: ['HARDSTYLE', 'HARDCORE_EDM', 'GABBER', 'HAPPY_HARDCORE', 'SPEEDCORE', 'JUMPSTYLE', 'HANDS_UP', 'DONK', 'MAKINA'],
  },
  {
    label: 'Эмбиент и даунтемпо',
    genres: [
      'AMBIENT', 'DARK_AMBIENT', 'NEW_AGE', 'BERLIN_SCHOOL', 'ILLBIENT', 'DRONE',
      'DUNGEON_SYNTH', 'DOWNTEMPO', 'CHILLWAVE', 'TRIP_HOP', 'LOFI', 'FUTURE_JAZZ',
      'ACID_JAZZ', 'JAZZDANCE',
    ],
  },
  {
    label: 'Синт, диско и ретро',
    genres: [
      'SYNTHPOP', 'SYNTHWAVE', 'VAPORWAVE', 'NEW_WAVE', 'DARKWAVE', 'ELECTROCLASH',
      'EBM', 'NEW_BEAT', 'DISCO', 'NU_DISCO', 'ITALO_DISCO', 'EURO_DISCO', 'HI_NRG',
      'EUROBEAT', 'EURODANCE', 'ITALODANCE', 'DISCO_POLO', 'DANCE_POP', 'FREESTYLE',
    ],
  },
  {
    label: 'Электроника: прочее',
    genres: [
      'ELECTRONIC', 'IDM', 'GLITCH', 'LEFTFIELD', 'CHIPTUNE', 'MUSIQUE_CONCRETE',
      'POWER_ELECTRONICS', 'RHYTHMIC_NOISE', 'SOUND_COLLAGE', 'TRIBAL',
    ],
  },
  {
    label: 'Хип-хоп и R&B',
    genres: [
      'HIPHOP', 'BOOMBAP', 'TRAP', 'DRILL', 'CLOUDRAP', 'PHONK', 'GANGSTA', 'G_FUNK',
      'HARDCORE_HIPHOP', 'HORRORCORE', 'CONSCIOUS', 'JAZZY_HIPHOP', 'INSTRUMENTAL_HIPHOP',
      'POP_RAP', 'CRUNK', 'BOUNCE', 'SCREW', 'MIAMI_BASS', 'BASS_MUSIC', 'BRITCORE',
      'RAGGA_HIPHOP', 'TURNTABLISM', 'CUT_UP_DJ', 'RNB', 'NEW_JACK_SWING',
    ],
  },
  {
    label: 'Соул и фанк',
    genres: [
      'SOUL', 'NEOSOUL', 'PSYCHEDELIC_SOUL', 'UK_STREET_SOUL', 'GOSPEL', 'FUNK',
      'P_FUNK', 'FREE_FUNK', 'BOOGIE', 'AFROBEAT',
    ],
  },
  {
    label: 'Рок',
    genres: [
      'ROCK', 'INDIE', 'ALTERNATIVE', 'CLASSIC_ROCK', 'HARD_ROCK', 'BLUES_ROCK',
      'ROCK_N_ROLL', 'ROCKABILLY', 'PSYCHOBILLY', 'SURF', 'BEAT', 'MOD', 'TWIST',
      'DOO_WOP', 'GARAGE_ROCK', 'GLAM', 'AOR', 'ARENA_ROCK', 'SOFT_ROCK', 'POP_ROCK',
      'POWER_POP', 'PUB_ROCK', 'FOLK_ROCK', 'COUNTRY_ROCK', 'SOUTHERN_ROCK',
      'PSYCHEDELIC', 'ACID_ROCK', 'SPACE_ROCK', 'PROGROCK', 'ART_ROCK', 'SYMPHONIC_ROCK',
      'KRAUTROCK', 'MATH_ROCK', 'POST_ROCK', 'SHOEGAZE', 'DREAMPOP', 'ETHEREAL',
      'GRUNGE', 'BRITPOP', 'YEYE',
    ],
  },
  {
    label: 'Панк и хардкор',
    genres: [
      'PUNK', 'HARDCORE_PUNK', 'MELODIC_HARDCORE', 'POST_HARDCORE', 'EMO', 'POP_PUNK',
      'OI', 'CRUST', 'POWER_VIOLENCE', 'NOISECORE', 'POSTPUNK', 'NO_WAVE', 'GOTH_ROCK',
      'DEATHROCK', 'COLDWAVE',
    ],
  },
  {
    label: 'Метал',
    genres: [
      'METAL', 'HEAVYMETAL', 'THRASH', 'SPEED_METAL', 'POWER_METAL', 'PROGRESSIVE_METAL',
      'DEATHMETAL', 'MELODIC_DEATH_METAL', 'TECHNICAL_DEATH_METAL', 'BLACKMETAL',
      'ATMOSPHERIC_BLACK_METAL', 'DEPRESSIVE_BLACK_METAL', 'VIKING_METAL', 'DOOM',
      'FUNERAL_DOOM', 'SLUDGE_METAL', 'STONER_ROCK', 'GRINDCORE', 'DEATHCORE',
      'METALCORE', 'POSTMETAL', 'NU_METAL', 'FOLK_METAL', 'FUNK_METAL', 'GOTHIC_METAL',
    ],
  },
  {
    label: 'Поп',
    genres: [
      'POP', 'INDIEPOP', 'HYPERPOP', 'BALLAD', 'BUBBLEGUM', 'EUROPOP',
      'CITY_POP', 'J_POP', 'K_POP', 'KAYOKYOKU', 'SCHLAGER', 'CHANSON', 'VOCAL',
      'NOVELTY', 'LIGHT_MUSIC', 'MUSIC_HALL', 'BOLLYWOOD', 'EASY_LISTENING', 'LOUNGE',
    ],
  },
  {
    label: 'Джаз',
    genres: [
      'JAZZ', 'BEBOP', 'HARD_BOP', 'POST_BOP', 'COOL_JAZZ', 'MODAL_JAZZ', 'FREE_JAZZ',
      'FREE_IMPROVISATION', 'AVANTGARDE_JAZZ', 'FUSION', 'JAZZ_FUNK', 'JAZZ_ROCK',
      'SWING', 'BIG_BAND', 'DIXIELAND', 'RAGTIME', 'GYPSY_JAZZ', 'SMOOTH_JAZZ',
      'CONTEMPORARY_JAZZ', 'SOUL_JAZZ', 'LATIN_JAZZ', 'AFRO_CUBAN_JAZZ', 'SPACE_AGE',
    ],
  },
  {
    label: 'Блюз',
    genres: [
      'BLUES', 'DELTA_BLUES', 'CHICAGO_BLUES', 'TEXAS_BLUES', 'LOUISIANA_BLUES',
      'COUNTRY_BLUES', 'ELECTRIC_BLUES', 'MODERN_ELECTRIC_BLUES', 'HARMONICA_BLUES',
      'PIANO_BLUES', 'JUMP_BLUES', 'BOOGIE_WOOGIE',
    ],
  },
  {
    label: 'Классика',
    genres: [
      'CLASSICAL', 'MEDIEVAL', 'RENAISSANCE', 'BAROQUE', 'ROMANTICISM', 'IMPRESSIONIST',
      'MODERN_CLASSICAL', 'CONTEMPORARY_CLASSICAL', 'POST_MODERN_CLASSICAL',
      'NEO_ROMANTIC', 'NEOCLASSICAL', 'CHORAL', 'OPERA', 'ORCHESTRAL', 'PIANO',
    ],
  },
  {
    label: 'Фолк и кантри',
    genres: [
      'FOLK', 'NEOFOLK', 'ACOUSTIC', 'SINGER_SONGWRITER', 'COUNTRY', 'BLUEGRASS',
      'HILLBILLY', 'HONKY_TONK', 'CAJUN', 'CELTIC', 'POLKA', 'VOLKSMUSIK',
    ],
  },
  {
    label: 'Этника',
    genres: [
      'WORLD', 'AFRICAN', 'HIGHLIFE', 'SOUKOUS', 'SEGA', 'RAI', 'ZOUK', 'PACIFIC',
      'NORDIC', 'ROMANI', 'FADO', 'FLAMENCO', 'CANZONE_NAPOLETANA', 'CATALAN_MUSIC',
      'LAIKO', 'ENTEKHNO', 'HINDUSTANI', 'INDIAN_CLASSICAL',
    ],
  },
  {
    label: 'Латино',
    genres: [
      'LATIN', 'REGGAETON', 'SALSA', 'CUMBIA', 'BOSSA_NOVA', 'SAMBA', 'BATUCADA',
      'BAIAO', 'FORRO', 'MPB', 'TANGO', 'BOLERO', 'MAMBO', 'CHA_CHA', 'RUMBA',
      'GUAGUANCO', 'GUAJIRA', 'GUARACHA', 'SON', 'SON_MONTUNO', 'AFRO_CUBAN', 'CUBANO',
      'DESCARGA', 'CHARANGA', 'PACHANGA', 'BOOGALOO', 'MERENGUE', 'VALLENATO', 'PORRO',
      'NUEVA_CANCION', 'RANCHERA', 'MARIACHI', 'NORTENO', 'TEJANO', 'BEGUINE', 'COMPAS',
    ],
  },
  {
    label: 'Регги и даб',
    genres: [
      'REGGAE', 'ROOTS_REGGAE', 'DANCEHALL', 'RAGGA', 'DUB', 'ROCKSTEADY', 'SKA',
      'LOVERS_ROCK', 'REGGAE_POP', 'CALYPSO', 'SOCA',
    ],
  },
  {
    label: 'Саундтрек и сцена',
    genres: ['SOUNDTRACK', 'CINEMATIC', 'MUSICAL', 'BRASS'],
  },
  {
    label: 'Эксперимент и прочее',
    genres: ['EXPERIMENTAL', 'NOISE', 'INDUSTRIAL', 'SPOKENWORD', 'FIELD_RECORDING'],
  },
];

export const ALL_GENRES: Genre[] = GENRE_GROUPS.flatMap((g) => g.genres);

// Runtime-гард для строк из jsonb (genre_suggestions), где enum не гарантирован
// на уровне типов. hasOwn, а не `in` — `in` смотрит и по цепочке прототипов,
// чем пропустил бы мусор вроде 'toString'.
export function isGenre(v: string): v is Genre {
  return Object.hasOwn(GENRE_LABELS, v);
}

// Подписи: русские для общеизвестных названий, английские — для сценовых имён.
export const GENRE_LABELS: Record<Genre, string> = {
  // Хаус
  HOUSE: 'House',
  DEEP_HOUSE: 'Deep House',
  TECH_HOUSE: 'Tech House',
  PROGRESSIVE_HOUSE: 'Progressive House',
  ELECTRO_HOUSE: 'Electro House',
  ACID_HOUSE: 'Acid House',
  ACID: 'Acid',
  GARAGE_HOUSE: 'Garage House',
  EURO_HOUSE: 'Euro House',
  ITALO_HOUSE: 'Italo House',
  HARD_HOUSE: 'Hard House',
  HIP_HOUSE: 'Hip House',
  GHETTO_HOUSE: 'Ghetto House',
  GHETTO: 'Ghettotech',
  TRIBAL_HOUSE: 'Tribal House',
  TROPICAL_HOUSE: 'Tropical House',
  BEATDOWN: 'Beatdown',
  // Техно
  TECHNO: 'Техно',
  MINIMAL_TECHNO: 'Minimal Techno',
  MINIMAL: 'Minimal',
  DEEP_TECHNO: 'Deep Techno',
  DUB_TECHNO: 'Dub Techno',
  HARD_TECHNO: 'Hard Techno',
  SCHRANZ: 'Schranz',
  BLEEP: 'Bleep',
  // Транс
  TRANCE: 'Транс',
  PROGRESSIVE_TRANCE: 'Progressive Trance',
  PSY_TRANCE: 'Psytrance',
  GOA_TRANCE: 'Goa Trance',
  HARD_TRANCE: 'Hard Trance',
  TECH_TRANCE: 'Tech Trance',
  // Бас, брейкбит и гараж
  DNB: 'Drum & Bass',
  JUNGLE: 'Jungle',
  DUBSTEP: 'Dubstep',
  HALFTIME: 'Halftime',
  GARAGE: 'UK Garage',
  SPEED_GARAGE: 'Speed Garage',
  BASSLINE: 'Bassline',
  GRIME: 'Грайм',
  BREAKBEAT: 'Breakbeat',
  BIG_BEAT: 'Big Beat',
  BREAKCORE: 'Breakcore',
  BROKEN_BEAT: 'Broken Beat',
  PROGRESSIVE_BREAKS: 'Progressive Breaks',
  JUKE: 'Juke / Footwork',
  ELECTRO: 'Electro',
  // Хардкор и хардстайл
  HARDSTYLE: 'Hardstyle',
  HARDCORE_EDM: 'Хардкор (рейв)',
  GABBER: 'Gabber',
  HAPPY_HARDCORE: 'Happy Hardcore',
  SPEEDCORE: 'Speedcore',
  JUMPSTYLE: 'Jumpstyle',
  HANDS_UP: 'Hands Up',
  DONK: 'Donk',
  MAKINA: 'Makina',
  // Эмбиент и даунтемпо
  AMBIENT: 'Эмбиент',
  DARK_AMBIENT: 'Dark Ambient',
  NEW_AGE: 'New Age',
  BERLIN_SCHOOL: 'Berlin School',
  ILLBIENT: 'Illbient',
  DRONE: 'Дроун',
  DUNGEON_SYNTH: 'Dungeon Synth',
  DOWNTEMPO: 'Downtempo',
  CHILLWAVE: 'Chillwave',
  TRIP_HOP: 'Трип-хоп',
  LOFI: 'Lo-fi',
  FUTURE_JAZZ: 'Future Jazz',
  ACID_JAZZ: 'Acid Jazz',
  JAZZDANCE: 'Jazzdance',
  // Синт, диско и ретро
  SYNTHPOP: 'Синти-поп',
  SYNTHWAVE: 'Synthwave',
  VAPORWAVE: 'Vaporwave',
  NEW_WAVE: 'Новая волна',
  DARKWAVE: 'Darkwave',
  ELECTROCLASH: 'Electroclash',
  EBM: 'EBM',
  NEW_BEAT: 'New Beat',
  DISCO: 'Диско',
  NU_DISCO: 'Nu-Disco',
  ITALO_DISCO: 'Italo Disco',
  EURO_DISCO: 'Euro Disco',
  HI_NRG: 'Hi-NRG',
  EUROBEAT: 'Eurobeat',
  EURODANCE: 'Eurodance',
  ITALODANCE: 'Italodance',
  DISCO_POLO: 'Disco Polo',
  DANCE_POP: 'Дэнс-поп',
  FREESTYLE: 'Freestyle',
  // Электроника: прочее
  ELECTRONIC: 'Электроника',
  IDM: 'IDM',
  GLITCH: 'Glitch',
  LEFTFIELD: 'Leftfield',
  CHIPTUNE: 'Chiptune',
  MUSIQUE_CONCRETE: 'Musique Concrète',
  POWER_ELECTRONICS: 'Power Electronics',
  RHYTHMIC_NOISE: 'Rhythmic Noise',
  SOUND_COLLAGE: 'Саунд-коллаж',
  TRIBAL: 'Tribal',
  // Хип-хоп и R&B
  HIPHOP: 'Хип-хоп',
  BOOMBAP: 'Boom Bap',
  TRAP: 'Трэп',
  DRILL: 'Дрилл',
  CLOUDRAP: 'Cloud Rap',
  PHONK: 'Фонк',
  GANGSTA: 'Гангста-рэп',
  G_FUNK: 'G-Funk',
  HARDCORE_HIPHOP: 'Хардкор-рэп',
  HORRORCORE: 'Horrorcore',
  CONSCIOUS: 'Conscious',
  JAZZY_HIPHOP: 'Джазовый хип-хоп',
  INSTRUMENTAL_HIPHOP: 'Инструментальный хип-хоп',
  POP_RAP: 'Поп-рэп',
  CRUNK: 'Crunk',
  BOUNCE: 'Bounce',
  SCREW: 'Screw',
  MIAMI_BASS: 'Miami Bass',
  BASS_MUSIC: 'Bass Music',
  BRITCORE: 'Britcore',
  RAGGA_HIPHOP: 'Ragga Hip-Hop',
  TURNTABLISM: 'Тёрнтейблизм',
  CUT_UP_DJ: 'Cut-up / DJ',
  RNB: 'R&B',
  NEW_JACK_SWING: 'New Jack Swing',
  // Соул и фанк
  SOUL: 'Соул',
  NEOSOUL: 'Neo-Soul',
  PSYCHEDELIC_SOUL: 'Психоделик-соул',
  UK_STREET_SOUL: 'UK Street Soul',
  GOSPEL: 'Госпел',
  FUNK: 'Фанк',
  P_FUNK: 'P-Funk',
  FREE_FUNK: 'Free Funk',
  BOOGIE: 'Boogie',
  AFROBEAT: 'Афробит',
  // Рок
  ROCK: 'Рок',
  INDIE: 'Инди',
  ALTERNATIVE: 'Альтернатива',
  CLASSIC_ROCK: 'Классический рок',
  HARD_ROCK: 'Хард-рок',
  BLUES_ROCK: 'Блюз-рок',
  ROCK_N_ROLL: 'Рок-н-ролл',
  ROCKABILLY: 'Рокабилли',
  PSYCHOBILLY: 'Психобилли',
  SURF: 'Сёрф',
  BEAT: 'Бит',
  MOD: 'Mod',
  TWIST: 'Твист',
  DOO_WOP: 'Doo-Wop',
  GARAGE_ROCK: 'Гаражный рок',
  GLAM: 'Глэм',
  AOR: 'AOR',
  ARENA_ROCK: 'Arena Rock',
  SOFT_ROCK: 'Софт-рок',
  POP_ROCK: 'Поп-рок',
  POWER_POP: 'Power Pop',
  PUB_ROCK: 'Pub Rock',
  FOLK_ROCK: 'Фолк-рок',
  COUNTRY_ROCK: 'Кантри-рок',
  SOUTHERN_ROCK: 'Южный рок',
  PSYCHEDELIC: 'Психоделика',
  ACID_ROCK: 'Acid Rock',
  SPACE_ROCK: 'Спейс-рок',
  PROGROCK: 'Прог-рок',
  ART_ROCK: 'Арт-рок',
  SYMPHONIC_ROCK: 'Симфо-рок',
  KRAUTROCK: 'Краут-рок',
  MATH_ROCK: 'Мат-рок',
  POST_ROCK: 'Пост-рок',
  SHOEGAZE: 'Shoegaze',
  DREAMPOP: 'Dream Pop',
  ETHEREAL: 'Ethereal',
  GRUNGE: 'Грандж',
  BRITPOP: 'Брит-поп',
  YEYE: 'Yé-Yé',
  // Панк и хардкор
  PUNK: 'Панк',
  HARDCORE_PUNK: 'Хардкор-панк',
  MELODIC_HARDCORE: 'Мелодик-хардкор',
  POST_HARDCORE: 'Пост-хардкор',
  EMO: 'Эмо',
  POP_PUNK: 'Поп-панк',
  OI: 'Oi!',
  CRUST: 'Краст',
  POWER_VIOLENCE: 'Powerviolence',
  NOISECORE: 'Noisecore',
  POSTPUNK: 'Пост-панк',
  NO_WAVE: 'No Wave',
  GOTH_ROCK: 'Готик-рок',
  DEATHROCK: 'Deathrock',
  COLDWAVE: 'Coldwave',
  // Метал
  METAL: 'Метал',
  HEAVYMETAL: 'Хэви-метал',
  THRASH: 'Трэш-метал',
  SPEED_METAL: 'Спид-метал',
  POWER_METAL: 'Пауэр-метал',
  PROGRESSIVE_METAL: 'Прогрессив-метал',
  DEATHMETAL: 'Дэт-метал',
  MELODIC_DEATH_METAL: 'Мелодик-дэт',
  TECHNICAL_DEATH_METAL: 'Техничный дэт',
  BLACKMETAL: 'Блэк-метал',
  ATMOSPHERIC_BLACK_METAL: 'Атмосферный блэк',
  DEPRESSIVE_BLACK_METAL: 'Депрессивный блэк',
  VIKING_METAL: 'Викинг-метал',
  DOOM: 'Дум',
  FUNERAL_DOOM: 'Фьюнерал-дум',
  SLUDGE_METAL: 'Сладж',
  STONER_ROCK: 'Стоунер',
  GRINDCORE: 'Грайндкор',
  DEATHCORE: 'Дэткор',
  METALCORE: 'Металкор',
  POSTMETAL: 'Пост-метал',
  NU_METAL: 'Ню-метал',
  FOLK_METAL: 'Фолк-метал',
  FUNK_METAL: 'Фанк-метал',
  GOTHIC_METAL: 'Готик-метал',
  // Поп
  POP: 'Поп',
  INDIEPOP: 'Инди-поп',
  HYPERPOP: 'Гиперпоп',
  BALLAD: 'Баллада',
  BUBBLEGUM: 'Bubblegum',
  EUROPOP: 'Европоп',
  CITY_POP: 'City Pop',
  J_POP: 'J-Pop',
  K_POP: 'K-Pop',
  KAYOKYOKU: 'Kayōkyoku',
  SCHLAGER: 'Шлягер',
  CHANSON: 'Шансон',
  VOCAL: 'Вокальная музыка',
  NOVELTY: 'Novelty',
  LIGHT_MUSIC: 'Лёгкая музыка',
  MUSIC_HALL: 'Мюзик-холл',
  BOLLYWOOD: 'Болливуд',
  EASY_LISTENING: 'Easy Listening',
  LOUNGE: 'Лаунж',
  // Джаз
  JAZZ: 'Джаз',
  BEBOP: 'Бибоп',
  HARD_BOP: 'Хард-боп',
  POST_BOP: 'Пост-боп',
  COOL_JAZZ: 'Кул-джаз',
  MODAL_JAZZ: 'Модальный джаз',
  FREE_JAZZ: 'Фри-джаз',
  FREE_IMPROVISATION: 'Свободная импровизация',
  AVANTGARDE_JAZZ: 'Авангардный джаз',
  FUSION: 'Фьюжн',
  JAZZ_FUNK: 'Джаз-фанк',
  JAZZ_ROCK: 'Джаз-рок',
  SWING: 'Свинг',
  BIG_BAND: 'Биг-бэнд',
  DIXIELAND: 'Диксиленд',
  RAGTIME: 'Рэгтайм',
  GYPSY_JAZZ: 'Цыганский джаз',
  SMOOTH_JAZZ: 'Smooth Jazz',
  CONTEMPORARY_JAZZ: 'Современный джаз',
  SOUL_JAZZ: 'Соул-джаз',
  LATIN_JAZZ: 'Латин-джаз',
  AFRO_CUBAN_JAZZ: 'Афро-кубинский джаз',
  SPACE_AGE: 'Space-Age',
  // Блюз
  BLUES: 'Блюз',
  DELTA_BLUES: 'Дельта-блюз',
  CHICAGO_BLUES: 'Чикагский блюз',
  TEXAS_BLUES: 'Техасский блюз',
  LOUISIANA_BLUES: 'Луизианский блюз',
  COUNTRY_BLUES: 'Кантри-блюз',
  ELECTRIC_BLUES: 'Электрический блюз',
  MODERN_ELECTRIC_BLUES: 'Современный электрический блюз',
  HARMONICA_BLUES: 'Блюз с гармоникой',
  PIANO_BLUES: 'Фортепианный блюз',
  JUMP_BLUES: 'Джамп-блюз',
  BOOGIE_WOOGIE: 'Буги-вуги',
  // Классика
  CLASSICAL: 'Классика',
  MEDIEVAL: 'Средневековая музыка',
  RENAISSANCE: 'Ренессанс',
  BAROQUE: 'Барокко',
  ROMANTICISM: 'Романтизм',
  IMPRESSIONIST: 'Импрессионизм',
  MODERN_CLASSICAL: 'Современная классика',
  CONTEMPORARY_CLASSICAL: 'Академический авангард',
  POST_MODERN_CLASSICAL: 'Постмодерн (академ.)',
  NEO_ROMANTIC: 'Неоромантизм',
  NEOCLASSICAL: 'Неоклассика',
  CHORAL: 'Хоровая музыка',
  OPERA: 'Опера',
  ORCHESTRAL: 'Оркестровое',
  PIANO: 'Фортепиано',
  // Фолк и кантри
  FOLK: 'Фолк',
  NEOFOLK: 'Неофолк',
  ACOUSTIC: 'Акустика',
  SINGER_SONGWRITER: 'Автор-исполнитель',
  COUNTRY: 'Кантри',
  BLUEGRASS: 'Блюграсс',
  HILLBILLY: 'Hillbilly',
  HONKY_TONK: 'Honky Tonk',
  CAJUN: 'Кажун',
  CELTIC: 'Кельтская музыка',
  POLKA: 'Полька',
  VOLKSMUSIK: 'Volksmusik',
  // Этника
  WORLD: 'Этника',
  AFRICAN: 'Африканская музыка',
  HIGHLIFE: 'Highlife',
  SOUKOUS: 'Soukous',
  SEGA: 'Séga',
  RAI: 'Raï',
  ZOUK: 'Zouk',
  PACIFIC: 'Музыка Океании',
  NORDIC: 'Скандинавская музыка',
  ROMANI: 'Цыганская музыка',
  FADO: 'Фаду',
  FLAMENCO: 'Фламенко',
  CANZONE_NAPOLETANA: 'Неаполитанская песня',
  CATALAN_MUSIC: 'Каталонская музыка',
  LAIKO: 'Laïkó',
  ENTEKHNO: 'Éntekhno',
  HINDUSTANI: 'Хиндустани',
  INDIAN_CLASSICAL: 'Индийская классика',
  // Латино
  LATIN: 'Латино',
  REGGAETON: 'Реггетон',
  SALSA: 'Сальса',
  CUMBIA: 'Кумбия',
  BOSSA_NOVA: 'Босса-нова',
  SAMBA: 'Самба',
  BATUCADA: 'Батукада',
  BAIAO: 'Baião',
  FORRO: 'Forró',
  MPB: 'MPB',
  TANGO: 'Танго',
  BOLERO: 'Болеро',
  MAMBO: 'Мамбо',
  CHA_CHA: 'Ча-ча-ча',
  RUMBA: 'Румба',
  GUAGUANCO: 'Guaguancó',
  GUAJIRA: 'Guajira',
  GUARACHA: 'Guaracha',
  SON: 'Сон',
  SON_MONTUNO: 'Сон-монтуно',
  AFRO_CUBAN: 'Афро-кубинская музыка',
  CUBANO: 'Cubano',
  DESCARGA: 'Descarga',
  CHARANGA: 'Charanga',
  PACHANGA: 'Пачанга',
  BOOGALOO: 'Бугалу',
  MERENGUE: 'Меренге',
  VALLENATO: 'Вальенато',
  PORRO: 'Porro',
  NUEVA_CANCION: 'Nueva Canción',
  RANCHERA: 'Ранчера',
  MARIACHI: 'Мариачи',
  NORTENO: 'Norteño',
  TEJANO: 'Tejano',
  BEGUINE: 'Beguine',
  COMPAS: 'Compas',
  // Регги и даб
  REGGAE: 'Регги',
  ROOTS_REGGAE: 'Рутс-регги',
  DANCEHALL: 'Дэнсхолл',
  RAGGA: 'Рагга',
  DUB: 'Даб',
  ROCKSTEADY: 'Рокстеди',
  SKA: 'Ска',
  LOVERS_ROCK: 'Lovers Rock',
  REGGAE_POP: 'Регги-поп',
  CALYPSO: 'Калипсо',
  SOCA: 'Сока',
  // Саундтрек и сцена
  SOUNDTRACK: 'Саундтрек',
  CINEMATIC: 'Кинематографик',
  MUSICAL: 'Мюзикл',
  BRASS: 'Духовой оркестр',
  // Эксперимент и прочее
  EXPERIMENTAL: 'Экспериментальное',
  NOISE: 'Нойз',
  INDUSTRIAL: 'Индастриал',
  SPOKENWORD: 'Spoken Word',
  FIELD_RECORDING: 'Полевые записи',
};
