import type { TrackGenre } from '@vire/db';
import { DISCOGS_400_LABELS } from './discogs-genre-labels.js';

export interface GenreSuggestion {
  genre: TrackGenre;
  confidence: number;
}

// Маппинг genre_discogs400 (таксономия Discogs "Parent---Subgenre") → наш genreEnum.
// Точечные сабжанры бьются в конкретные значения нашего enum; широкие/непересекающиеся
// категории (Latin, Non-Music кроме Spoken Word, Children's, Brass & Military) — либо
// сведены к ближайшему по духу значению (WORLD), либо отброшены осознанно (не бьются
// ни во что осмысленное). Часть решений — эвристика по жанровой близости, не наука.
export const DISCOGS_TO_GENRE: Readonly<Record<string, TrackGenre>> = {
  // Blues
  'Blues---Boogie Woogie': 'BLUES',
  'Blues---Chicago Blues': 'BLUES',
  'Blues---Country Blues': 'BLUES',
  'Blues---Delta Blues': 'BLUES',
  'Blues---Electric Blues': 'BLUES',
  'Blues---Harmonica Blues': 'BLUES',
  'Blues---Jump Blues': 'BLUES',
  'Blues---Louisiana Blues': 'BLUES',
  'Blues---Modern Electric Blues': 'BLUES',
  'Blues---Piano Blues': 'BLUES',
  'Blues---Rhythm & Blues': 'RNB',
  'Blues---Texas Blues': 'BLUES',

  // Classical
  'Classical---Baroque': 'CLASSICAL',
  'Classical---Choral': 'CLASSICAL',
  'Classical---Classical': 'CLASSICAL',
  'Classical---Contemporary': 'CLASSICAL',
  'Classical---Impressionist': 'CLASSICAL',
  'Classical---Medieval': 'CLASSICAL',
  'Classical---Modern': 'CLASSICAL',
  'Classical---Neo-Classical': 'NEOCLASSICAL',
  'Classical---Neo-Romantic': 'CLASSICAL',
  'Classical---Opera': 'OPERA',
  'Classical---Post-Modern': 'CLASSICAL',
  'Classical---Renaissance': 'CLASSICAL',
  'Classical---Romantic': 'CLASSICAL',

  // Electronic
  'Electronic---Abstract': 'EXPERIMENTAL',
  'Electronic---Acid': 'HOUSE',
  'Electronic---Acid House': 'HOUSE',
  'Electronic---Acid Jazz': 'FUNK',
  'Electronic---Ambient': 'AMBIENT',
  'Electronic---Bassline': 'GARAGE',
  'Electronic---Berlin-School': 'AMBIENT',
  'Electronic---Big Beat': 'BREAKBEAT',
  'Electronic---Bleep': 'TECHNO',
  'Electronic---Breakbeat': 'BREAKBEAT',
  'Electronic---Breakcore': 'BREAKBEAT',
  'Electronic---Breaks': 'BREAKBEAT',
  'Electronic---Broken Beat': 'BREAKBEAT',
  'Electronic---Chillwave': 'DOWNTEMPO',
  'Electronic---Dance-pop': 'POP',
  'Electronic---Dark Ambient': 'AMBIENT',
  'Electronic---Darkwave': 'SYNTHPOP',
  'Electronic---Deep House': 'HOUSE',
  'Electronic---Deep Techno': 'TECHNO',
  'Electronic---Disco': 'FUNK',
  'Electronic---Downtempo': 'DOWNTEMPO',
  'Electronic---Drone': 'DRONE',
  'Electronic---Drum n Bass': 'DNB',
  'Electronic---Dub': 'DUB',
  'Electronic---Dub Techno': 'DUB',
  'Electronic---Dubstep': 'DUBSTEP',
  'Electronic---Dungeon Synth': 'DRONE',
  'Electronic---EBM': 'INDUSTRIAL',
  'Electronic---Electro': 'ELECTRONIC',
  'Electronic---Electro House': 'HOUSE',
  'Electronic---Electroclash': 'SYNTHPOP',
  'Electronic---Euro House': 'HOUSE',
  'Electronic---Euro-Disco': 'POP',
  'Electronic---Eurobeat': 'POP',
  'Electronic---Eurodance': 'POP',
  'Electronic---Experimental': 'EXPERIMENTAL',
  'Electronic---Freestyle': 'ELECTRONIC',
  'Electronic---Future Jazz': 'FUSION',
  'Electronic---Gabber': 'HARDSTYLE',
  'Electronic---Garage House': 'HOUSE',
  'Electronic---Ghetto House': 'HOUSE',
  'Electronic---Glitch': 'IDM',
  'Electronic---Goa Trance': 'TRANCE',
  'Electronic---Grime': 'HIPHOP',
  'Electronic---Halftime': 'DUBSTEP',
  'Electronic---Hands Up': 'HARDSTYLE',
  'Electronic---Happy Hardcore': 'HARDSTYLE',
  'Electronic---Hard House': 'HOUSE',
  'Electronic---Hard Techno': 'TECHNO',
  'Electronic---Hard Trance': 'TRANCE',
  'Electronic---Hardcore': 'HARDSTYLE',
  'Electronic---Hardstyle': 'HARDSTYLE',
  'Electronic---Hi NRG': 'POP',
  'Electronic---Hip Hop': 'HIPHOP',
  'Electronic---Hip-House': 'HOUSE',
  'Electronic---House': 'HOUSE',
  'Electronic---IDM': 'IDM',
  'Electronic---Illbient': 'AMBIENT',
  'Electronic---Industrial': 'INDUSTRIAL',
  'Electronic---Italo House': 'HOUSE',
  'Electronic---Italo-Disco': 'SYNTHPOP',
  'Electronic---Italodance': 'POP',
  'Electronic---Jazzdance': 'FUSION',
  'Electronic---Juke': 'BREAKBEAT',
  'Electronic---Jumpstyle': 'HARDSTYLE',
  'Electronic---Jungle': 'DNB',
  'Electronic---Latin': 'WORLD',
  'Electronic---Leftfield': 'EXPERIMENTAL',
  'Electronic---Makina': 'HARDSTYLE',
  'Electronic---Minimal': 'TECHNO',
  'Electronic---Minimal Techno': 'TECHNO',
  'Electronic---Modern Classical': 'NEOCLASSICAL',
  'Electronic---Musique Concrète': 'EXPERIMENTAL',
  'Electronic---Neofolk': 'FOLK',
  'Electronic---New Age': 'AMBIENT',
  'Electronic---New Beat': 'INDUSTRIAL',
  'Electronic---New Wave': 'SYNTHPOP',
  'Electronic---Noise': 'NOISE',
  'Electronic---Nu-Disco': 'FUNK',
  'Electronic---Power Electronics': 'INDUSTRIAL',
  'Electronic---Progressive Breaks': 'BREAKBEAT',
  'Electronic---Progressive House': 'HOUSE',
  'Electronic---Progressive Trance': 'TRANCE',
  'Electronic---Psy-Trance': 'TRANCE',
  'Electronic---Rhythmic Noise': 'INDUSTRIAL',
  'Electronic---Schranz': 'TECHNO',
  'Electronic---Sound Collage': 'EXPERIMENTAL',
  'Electronic---Speed Garage': 'GARAGE',
  'Electronic---Speedcore': 'HARDSTYLE',
  'Electronic---Synth-pop': 'SYNTHPOP',
  'Electronic---Synthwave': 'SYNTHWAVE',
  'Electronic---Tech House': 'HOUSE',
  'Electronic---Tech Trance': 'TRANCE',
  'Electronic---Techno': 'TECHNO',
  'Electronic---Trance': 'TRANCE',
  'Electronic---Tribal': 'WORLD',
  'Electronic---Tribal House': 'HOUSE',
  'Electronic---Trip Hop': 'DOWNTEMPO',
  'Electronic---Tropical House': 'HOUSE',
  'Electronic---UK Garage': 'GARAGE',
  'Electronic---Vaporwave': 'SYNTHWAVE',

  // Folk, World, & Country
  'Folk, World, & Country---African': 'WORLD',
  'Folk, World, & Country---Bluegrass': 'COUNTRY',
  'Folk, World, & Country---Cajun': 'FOLK',
  'Folk, World, & Country---Celtic': 'FOLK',
  'Folk, World, & Country---Country': 'COUNTRY',
  'Folk, World, & Country---Fado': 'WORLD',
  'Folk, World, & Country---Flamenco': 'WORLD',
  'Folk, World, & Country---Folk': 'FOLK',
  'Folk, World, & Country---Gospel': 'SOUL',
  'Folk, World, & Country---Highlife': 'WORLD',
  'Folk, World, & Country---Hillbilly': 'COUNTRY',
  'Folk, World, & Country---Hindustani': 'WORLD',
  'Folk, World, & Country---Honky Tonk': 'COUNTRY',
  'Folk, World, & Country---Indian Classical': 'WORLD',
  'Folk, World, & Country---Laïkó': 'WORLD',
  'Folk, World, & Country---Nordic': 'WORLD',
  'Folk, World, & Country---Pacific': 'WORLD',
  'Folk, World, & Country---Polka': 'FOLK',
  'Folk, World, & Country---Raï': 'WORLD',
  'Folk, World, & Country---Romani': 'WORLD',
  'Folk, World, & Country---Soukous': 'WORLD',
  'Folk, World, & Country---Séga': 'WORLD',
  'Folk, World, & Country---Volksmusik': 'FOLK',
  'Folk, World, & Country---Zouk': 'WORLD',
  'Folk, World, & Country---Éntekhno': 'WORLD',

  // Funk / Soul
  'Funk / Soul---Afrobeat': 'FUNK',
  'Funk / Soul---Boogie': 'FUNK',
  'Funk / Soul---Contemporary R&B': 'RNB',
  'Funk / Soul---Disco': 'FUNK',
  'Funk / Soul---Free Funk': 'FUNK',
  'Funk / Soul---Funk': 'FUNK',
  'Funk / Soul---Gospel': 'SOUL',
  'Funk / Soul---Neo Soul': 'NEOSOUL',
  'Funk / Soul---New Jack Swing': 'RNB',
  'Funk / Soul---P.Funk': 'FUNK',
  'Funk / Soul---Psychedelic': 'SOUL',
  'Funk / Soul---Rhythm & Blues': 'RNB',
  'Funk / Soul---Soul': 'SOUL',
  'Funk / Soul---Swingbeat': 'RNB',
  'Funk / Soul---UK Street Soul': 'SOUL',

  // Hip Hop
  'Hip Hop---Boom Bap': 'BOOMBAP',
  'Hip Hop---Bounce': 'HIPHOP',
  'Hip Hop---Britcore': 'HIPHOP',
  'Hip Hop---Cloud Rap': 'CLOUDRAP',
  'Hip Hop---Conscious': 'HIPHOP',
  'Hip Hop---Crunk': 'HIPHOP',
  'Hip Hop---Cut-up/DJ': 'HIPHOP',
  'Hip Hop---Electro': 'HIPHOP',
  'Hip Hop---G-Funk': 'HIPHOP',
  'Hip Hop---Gangsta': 'HIPHOP',
  'Hip Hop---Grime': 'HIPHOP',
  'Hip Hop---Hardcore Hip-Hop': 'HIPHOP',
  'Hip Hop---Horrorcore': 'HIPHOP',
  'Hip Hop---Instrumental': 'HIPHOP',
  'Hip Hop---Jazzy Hip-Hop': 'HIPHOP',
  'Hip Hop---Miami Bass': 'HIPHOP',
  'Hip Hop---Pop Rap': 'HIPHOP',
  'Hip Hop---Ragga HipHop': 'HIPHOP',
  'Hip Hop---RnB/Swing': 'RNB',
  'Hip Hop---Screw': 'HIPHOP',
  'Hip Hop---Thug Rap': 'HIPHOP',
  'Hip Hop---Trap': 'TRAP',
  'Hip Hop---Trip Hop': 'DOWNTEMPO',
  'Hip Hop---Turntablism': 'HIPHOP',

  // Jazz
  'Jazz---Afro-Cuban Jazz': 'JAZZ',
  'Jazz---Afrobeat': 'JAZZ',
  'Jazz---Avant-garde Jazz': 'JAZZ',
  'Jazz---Big Band': 'SWING',
  'Jazz---Bop': 'BEBOP',
  'Jazz---Bossa Nova': 'JAZZ',
  'Jazz---Contemporary Jazz': 'JAZZ',
  'Jazz---Cool Jazz': 'JAZZ',
  'Jazz---Dixieland': 'JAZZ',
  'Jazz---Easy Listening': 'JAZZ',
  'Jazz---Free Improvisation': 'EXPERIMENTAL',
  'Jazz---Free Jazz': 'JAZZ',
  'Jazz---Fusion': 'FUSION',
  'Jazz---Gypsy Jazz': 'JAZZ',
  'Jazz---Hard Bop': 'BEBOP',
  'Jazz---Jazz-Funk': 'FUSION',
  'Jazz---Jazz-Rock': 'FUSION',
  'Jazz---Latin Jazz': 'JAZZ',
  'Jazz---Modal': 'JAZZ',
  'Jazz---Post Bop': 'JAZZ',
  'Jazz---Ragtime': 'JAZZ',
  'Jazz---Smooth Jazz': 'JAZZ',
  'Jazz---Soul-Jazz': 'JAZZ',
  'Jazz---Swing': 'SWING',

  // Latin — сведены к WORLD (нет отдельного бакета в нашем enum)
  'Latin---Afro-Cuban': 'WORLD', 'Latin---Baião': 'WORLD', 'Latin---Batucada': 'WORLD',
  'Latin---Beguine': 'WORLD', 'Latin---Bolero': 'WORLD', 'Latin---Boogaloo': 'WORLD',
  'Latin---Bossanova': 'WORLD', 'Latin---Cha-Cha': 'WORLD', 'Latin---Charanga': 'WORLD',
  'Latin---Compas': 'WORLD', 'Latin---Cubano': 'WORLD', 'Latin---Cumbia': 'WORLD',
  'Latin---Descarga': 'WORLD', 'Latin---Forró': 'WORLD', 'Latin---Guaguancó': 'WORLD',
  'Latin---Guajira': 'WORLD', 'Latin---Guaracha': 'WORLD', 'Latin---MPB': 'WORLD',
  'Latin---Mambo': 'WORLD', 'Latin---Mariachi': 'WORLD', 'Latin---Merengue': 'WORLD',
  'Latin---Norteño': 'WORLD', 'Latin---Nueva Cancion': 'WORLD', 'Latin---Pachanga': 'WORLD',
  'Latin---Porro': 'WORLD', 'Latin---Ranchera': 'WORLD', 'Latin---Reggaeton': 'WORLD',
  'Latin---Rumba': 'WORLD', 'Latin---Salsa': 'WORLD', 'Latin---Samba': 'WORLD',
  'Latin---Son': 'WORLD', 'Latin---Son Montuno': 'WORLD', 'Latin---Tango': 'WORLD',
  'Latin---Tejano': 'WORLD', 'Latin---Vallenato': 'WORLD',

  // Non-Music — почти всё отбрасываем, кроме явного spoken word
  'Non-Music---Poetry': 'SPOKENWORD',
  'Non-Music---Spoken Word': 'SPOKENWORD',

  // Pop
  'Pop---Ballad': 'POP',
  'Pop---Bollywood': 'WORLD',
  'Pop---Bubblegum': 'POP',
  'Pop---Chanson': 'POP',
  'Pop---City Pop': 'POP',
  'Pop---Europop': 'POP',
  'Pop---Indie Pop': 'INDIEPOP',
  'Pop---J-pop': 'POP',
  'Pop---K-pop': 'POP',
  'Pop---Kayōkyoku': 'POP',
  'Pop---Light Music': 'POP',
  'Pop---Music Hall': 'POP',
  'Pop---Novelty': 'POP',
  'Pop---Schlager': 'POP',
  'Pop---Vocal': 'POP',

  // Reggae
  'Reggae---Calypso': 'WORLD',
  'Reggae---Dancehall': 'REGGAE',
  'Reggae---Dub': 'DUB',
  'Reggae---Lovers Rock': 'REGGAE',
  'Reggae---Ragga': 'REGGAE',
  'Reggae---Reggae': 'REGGAE',
  'Reggae---Reggae-Pop': 'REGGAE',
  'Reggae---Rocksteady': 'REGGAE',
  'Reggae---Roots Reggae': 'REGGAE',
  'Reggae---Ska': 'REGGAE',
  'Reggae---Soca': 'WORLD',

  // Rock
  'Rock---AOR': 'ROCK',
  'Rock---Acid Rock': 'PSYCHEDELIC',
  'Rock---Acoustic': 'ACOUSTIC',
  'Rock---Alternative Rock': 'ALTERNATIVE',
  'Rock---Arena Rock': 'ROCK',
  'Rock---Art Rock': 'PROGROCK',
  'Rock---Atmospheric Black Metal': 'BLACKMETAL',
  'Rock---Avantgarde': 'EXPERIMENTAL',
  'Rock---Beat': 'ROCK',
  'Rock---Black Metal': 'BLACKMETAL',
  'Rock---Blues Rock': 'BLUES',
  'Rock---Brit Pop': 'INDIE',
  'Rock---Classic Rock': 'ROCK',
  'Rock---Coldwave': 'POSTPUNK',
  'Rock---Country Rock': 'COUNTRY',
  'Rock---Crust': 'PUNK',
  'Rock---Death Metal': 'DEATHMETAL',
  'Rock---Deathcore': 'METALCORE',
  'Rock---Deathrock': 'POSTPUNK',
  'Rock---Depressive Black Metal': 'BLACKMETAL',
  'Rock---Doo Wop': 'ROCK',
  'Rock---Doom Metal': 'DOOM',
  'Rock---Dream Pop': 'DREAMPOP',
  'Rock---Emo': 'ALTERNATIVE',
  'Rock---Ethereal': 'DREAMPOP',
  'Rock---Experimental': 'EXPERIMENTAL',
  'Rock---Folk Metal': 'METAL',
  'Rock---Folk Rock': 'FOLK',
  'Rock---Funeral Doom Metal': 'DOOM',
  'Rock---Funk Metal': 'METAL',
  'Rock---Garage Rock': 'ROCK',
  'Rock---Glam': 'ROCK',
  'Rock---Goregrind': 'DEATHMETAL',
  'Rock---Goth Rock': 'POSTPUNK',
  'Rock---Gothic Metal': 'METAL',
  'Rock---Grindcore': 'DEATHMETAL',
  'Rock---Grunge': 'GRUNGE',
  'Rock---Hard Rock': 'ROCK',
  'Rock---Hardcore': 'PUNK',
  'Rock---Heavy Metal': 'HEAVYMETAL',
  'Rock---Indie Rock': 'INDIE',
  'Rock---Industrial': 'INDUSTRIAL',
  'Rock---Krautrock': 'EXPERIMENTAL',
  'Rock---Lo-Fi': 'LOFI',
  'Rock---Lounge': 'DOWNTEMPO',
  'Rock---Math Rock': 'PROGROCK',
  'Rock---Melodic Death Metal': 'DEATHMETAL',
  'Rock---Melodic Hardcore': 'PUNK',
  'Rock---Metalcore': 'METALCORE',
  'Rock---Mod': 'ROCK',
  'Rock---Neofolk': 'FOLK',
  'Rock---New Wave': 'SYNTHPOP',
  'Rock---No Wave': 'EXPERIMENTAL',
  'Rock---Noise': 'NOISE',
  'Rock---Noisecore': 'NOISE',
  'Rock---Nu Metal': 'METAL',
  'Rock---Oi': 'PUNK',
  'Rock---Pop Punk': 'PUNK',
  'Rock---Pop Rock': 'POP',
  'Rock---Post Rock': 'PROGROCK',
  'Rock---Post-Hardcore': 'PUNK',
  'Rock---Post-Metal': 'POSTMETAL',
  'Rock---Post-Punk': 'POSTPUNK',
  'Rock---Power Metal': 'HEAVYMETAL',
  'Rock---Power Pop': 'INDIEPOP',
  'Rock---Power Violence': 'PUNK',
  'Rock---Prog Rock': 'PROGROCK',
  'Rock---Progressive Metal': 'METAL',
  'Rock---Psychedelic Rock': 'PSYCHEDELIC',
  'Rock---Psychobilly': 'PUNK',
  'Rock---Pub Rock': 'ROCK',
  'Rock---Punk': 'PUNK',
  'Rock---Rock & Roll': 'ROCK',
  'Rock---Rockabilly': 'ROCK',
  'Rock---Shoegaze': 'SHOEGAZE',
  'Rock---Ska': 'REGGAE',
  'Rock---Sludge Metal': 'DOOM',
  'Rock---Soft Rock': 'ROCK',
  'Rock---Southern Rock': 'ROCK',
  'Rock---Space Rock': 'PSYCHEDELIC',
  'Rock---Speed Metal': 'HEAVYMETAL',
  'Rock---Stoner Rock': 'DOOM',
  'Rock---Surf': 'ROCK',
  'Rock---Symphonic Rock': 'PROGROCK',
  'Rock---Technical Death Metal': 'DEATHMETAL',
  'Rock---Thrash': 'HEAVYMETAL',
  'Rock---Twist': 'ROCK',
  'Rock---Viking Metal': 'BLACKMETAL',
  'Rock---Yé-Yé': 'POP',

  // Stage & Screen
  'Stage & Screen---Musical': 'SOUNDTRACK',
  'Stage & Screen---Score': 'SOUNDTRACK',
  'Stage & Screen---Soundtrack': 'SOUNDTRACK',
  'Stage & Screen---Theme': 'SOUNDTRACK',
};

// Метки, которых нет в списке выше, осознанно отброшены (Brass & Military, Children's,
// большая часть Non-Music, нишевые Discogs-стили без аналога в нашем enum).

/** Все метки маппинга реально существуют в списке модели — страховка от опечаток. */
const KNOWN_LABELS = new Set(DISCOGS_400_LABELS);
for (const label of Object.keys(DISCOGS_TO_GENRE)) {
  if (!KNOWN_LABELS.has(label)) {
    throw new Error(`DISCOGS_TO_GENRE: неизвестная метка "${label}" — нет в DISCOGS_400_LABELS`);
  }
}

/**
 * Агрегирует сырые предсказания модели (400 меток Discogs) в топ-5 наших жанров.
 * Confidence суммируется по всем discogs-меткам, попавшим в один наш жанр, затем
 * нормализуется на сумму по ВСЕМ замэпленным меткам (не по всем 400) — так остаток
 * массы, ушедший в отброшенные метки, не занижает уверенность искусственно.
 */
export function mapDiscogsPredictionsToGenres(
  probabilities: ArrayLike<number>,
): GenreSuggestion[] {
  const sums = new Map<TrackGenre, number>();
  let total = 0;

  for (let i = 0; i < DISCOGS_400_LABELS.length && i < probabilities.length; i++) {
    const genre = DISCOGS_TO_GENRE[DISCOGS_400_LABELS[i]];
    if (!genre) continue;
    const p = probabilities[i];
    if (p <= 0) continue;
    sums.set(genre, (sums.get(genre) ?? 0) + p);
    total += p;
  }

  if (total <= 0) return [];

  return Array.from(sums.entries())
    .map(([genre, sum]) => ({ genre, confidence: sum / total }))
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 5);
}
