// АВТО-СГЕНЕРИРОВАНО: node scripts/build-icons.mjs — не править руками.
// Источник: папка icons/{system,social,streaming,brand-glyph}/*.svg

export const SYSTEM_ICON_NAMES = [
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'arrow-left',
  'arrow-left-circle',
  'arrow-right',
  'arrow-right-circle',
  'award',
  'ban',
  'bell',
  'bell-off',
  'bold',
  'bookmark',
  'calendar',
  'check',
  'check-square',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'clipboard',
  'clock',
  'coffee',
  'columns',
  'copy',
  'corner-down-right',
  'edit',
  'edit-2',
  'edit-3',
  'external-link',
  'eye',
  'eye-off',
  'fast-forward',
  'file',
  'file-minus',
  'file-plus',
  'file-text',
  'filter',
  'globe',
  'grid',
  'hash',
  'heart',
  'help-circle',
  'home',
  'image',
  'info',
  'italic',
  'layers',
  'layout',
  'link',
  'link-2',
  'list',
  'list-plus',
  'loader',
  'lock',
  'log-in',
  'log-out',
  'mail',
  'maximize',
  'maximize-2',
  'menu',
  'message-square',
  'mic',
  'minimize',
  'minimize-2',
  'minus-square',
  'more-horizontal',
  'more-vertical',
  'music',
  'paperclip',
  'pause',
  'pause-circle',
  'phone',
  'pie-chart',
  'play',
  'play-circle',
  'plus',
  'plus-circle',
  'printer',
  'refresh-cw',
  'repeat',
  'rewind',
  'rotate-ccw',
  'save',
  'search',
  'server',
  'settings',
  'share-2',
  'shuffle',
  'sidebar',
  'skip-back',
  'skip-forward',
  'sliders',
  'square',
  'star',
  'table',
  'terminal',
  'text',
  'thumbs-down',
  'thumbs-up',
  'toggle-left',
  'toggle-right',
  'trash',
  'trash-2',
  'underline',
  'unlock',
  'upload',
  'user',
  'user-check',
  'user-minus',
  'user-plus',
  'user-x',
  'users',
  'volume',
  'volume-1',
  'volume-2',
  'volume-x',
  'wrench',
  'x',
  'x-circle',
  'zoom-in',
  'zoom-out',
] as const;

export const SOCIAL_ICON_NAMES = [
  'bandlab',
  'bandsintown',
  'bluesky',
  'discord',
  'facebook',
  'instagram',
  'telegram',
  'tiktok',
  'twitch',
  'vk',
  'x',
  'youtube',
] as const;

// Компактные квадратные глифы брендов (для мелких строк редактора). Источник:
// icons/brand-glyph/*.svg. Вордмарки (icons/{social,streaming}) — отдельно, их
// используют лендинги смартлинков.
export const BRAND_GLYPH_NAMES = [
  'amazon-music',
  'apple-music',
  'bandcamp',
  'bluesky',
  'deezer',
  'facebook',
  'instagram',
  'kion-music',
  'soundcloud',
  'spotify',
  'telegram',
  'tidal',
  'tiktok',
  'twitch',
  'vk',
  'vk-music',
  'x',
  'yandex-music',
  'youtube',
  'youtube-music',
  'zvuk',
] as const;

export const STREAMING_ICON_NAMES = [
  'amazon-music',
  'apple-music',
  'bandcamp',
  'deezer',
  'kion-music',
  'soundcloud',
  'spotify',
  'tidal',
  'vk-music',
  'yandex-music',
  'youtube-music',
  'zvuk',
] as const;

/** Соотношение сторон бренд-лого (ширина/высота). >2.2 — вордмарк (с текстом). */
export const BRAND_RATIO: Record<string, number> = {
  'bandlab': 4.393,
  'bandsintown': 6.57,
  'bluesky': 4.486,
  'discord': 6.256,
  'facebook': 1,
  'instagram': 1,
  'telegram': 1,
  'tiktok': 4.43,
  'twitch': 1.62,
  'vk': 1,
  'x': 0.979,
  'youtube': 4.633,
  'amazon-music': 5,
  'apple-music': 4.13,
  'bandcamp': 6.35,
  'deezer': 3.604,
  'kion-music': 8.4,
  'soundcloud': 8.83,
  'spotify': 4.163,
  'tidal': 7.074,
  'vk-music': 5.11,
  'yandex-music': 8.364,
  'youtube-music': 2.924,
  'zvuk': 3.904,
};
